---
title: "vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(Project4520)
```

## provided code for subseting to the points in USA
```{r}
# get the polygon defining the continental USA
library("maps")
library("sp")
usa_poly <- map("usa")
usa_poly$x <- c(NA,usa_poly$x,NA)
usa_poly$y <- c(NA,usa_poly$y,NA)
nai <- which(is.na( usa_poly$x ))

# define a grid of longitude and latitude points
n1 <- 180
n2 <- 90
lo <- seq(usa_poly$range[1], usa_poly$range[2], length.out = n1)
la <- seq(usa_poly$range[3], usa_poly$range[4], length.out = n2)
lonlat_grid <- as.matrix( expand.grid( lo, la ) )

# figure out which points are inside USA
in_usa <- rep(FALSE, nrow(lonlat_grid))
for(j in 1:(length(nai)-1)){
    in_this <- sp::point.in.polygon(
        lonlat_grid[,1],
        lonlat_grid[,2],
        usa_poly$x[(nai[j]+1):(nai[j+1]-1)],
        usa_poly$y[(nai[j]+1):(nai[j+1]-1)]
    )
    in_usa <- in_usa | in_this
}

# subset to the points in USA
lonlat_usa <- as.matrix(lonlat_grid[in_usa,])
```

## Part 2 Q1
```{r}
# reference https://map-rfun.library.duke.edu/01_georeference.html
# create a dataframe that includes, airport code, longitude, latitude, and nunmber of 
# non-stop destination
airport_df <- airport_data
num_destination <- matrix(0,nrow=length(direct_from),ncol=1)
for (i in 1:length(direct_from))
  num_destination[i,] <- length(direct_from[[i]])
airport_df <- cbind(airport_df,num_destination)
```

### Create a map containing all the airports in the original grids
```{r fig.width= 9, fig.height= 9}
library(mapview)
library(tidyverse)
library(sf)

# Create the map 
map.airport <- mapview(airport_df, xcol = "longitude.degree", ycol = "latitude.degree",zcol="num_destination",crs = 4269, grid = FALSE)
map.airport
```

### Create a map containing only the airports in Continental USA that is inside the usa_poly
```{r fig.width= 8, fig.height= 8}
lonlat_airport <- airport_df

# get the polygon defining the continental USA
# library(maps)
# library(sp)
# usa_poly <- map("usa")
# usa_poly$x <- c(NA,usa_poly$x,NA)
# usa_poly$y <- c(NA,usa_poly$y,NA)
# nai <- which(is.na( usa_poly$x ))

in_usa <- rep(FALSE, nrow(lonlat_airport))
for(j in 1:(length(nai)-1)){
    in_this <- sp::point.in.polygon(
        lonlat_airport[,2],
        lonlat_airport[,3],
        usa_poly$x[(nai[j]+1):(nai[j+1]-1)],
        usa_poly$y[(nai[j]+1):(nai[j+1]-1)]
    )
    in_usa <- in_usa | in_this
}

# subset to the points in continental USA
continent_df <- data.frame(lonlat_airport[in_usa,])
# save the continent_df for further usage in Part 2 problem 4
#save(continent_df, file = "/Users/shirley/Desktop/statcomp2022/BTRY_4520/Project4520/data/continent_df.RData")


map.airport <- mapview(continent_df, xcol = "longitude.degree", 
                       ycol ="latitude.degree",zcol="num_destination",
                       crs = 4269, grid=FALSE)
map.airport
```

## Part2 Q2:
```{r}
# reachable_points <- function(data,lonlat,x){
#   results <- rep(FALSE, nrow(data))
#   dists <- sp::spDistsN1(data, lonlat, longlat = TRUE)
#   # part (a)
#   # Check if within crow distance
#   # Convert dists from km to miles
#   dists <- dists / 1.60934
#   in_crow_dist <- which(dists <= 2*x)
#   results[in_crow_dist] <- TRUE
#   
#   # part (b)
#   airports <- airports_nearby(lonlat, airport_data, x)
#   
#   # check if there's airports near by
#   if (nrow(airports)==1 & is.na(airports[1,]$airport_code)==TRUE) {
#     reachable_df <- data.frame(data[results,])
#     return(reachable_df) # no airports nearby and just return condition a
#   } else {
#     airports_in_one_flight <- c()
#     for(i in 1:nrow(airports)){
#       airport_code <- airports[i,1]
#       dests <- direct_from[[airport_code]]
#       airports_in_one_flight <- append(airports_in_one_flight, dests)
#     }
#     airports_in_one_flight <- unique(airports_in_one_flight)
#     
#     ports_lonlat <- airport_data[airport_data$airport_code %in% airports_in_one_flight, 2:3]
#     for(i in 1:nrow(ports_lonlat)){
#       port_dists <- sp::spDistsN1(data, c(ports_lonlat[i,1], ports_lonlat[i,2]), longlat = TRUE)
#       port_dists <- port_dists / 1.60934
#       in_dist <- which(port_dists <= x)
#       results[in_dist] <- TRUE
#     }
#     reachable_df <- data.frame(data[results,])
#     return(reachable_df)
#   }
# }
```

```{r}
# calculate proportion of grid points are reachable
proportion.val <- function(reachable_df) {
  prop <- nrow(reachable_df) / nrow(lonlat_usa)
  return (prop)
}
```

### Using Ithaca as an example:

```{r fig.width= 8, fig.height= 8}
# x = 75 miles
library("ggplot2")
library("maps")
ithaca_lonlat <- matrix(c(-76.45872,42.49136), ncol = 2, nrow = 1)
ithaca <- reachable_points(lonlat_usa,ithaca_lonlat,75,df = df_in_USA, ad = continent_df[,1:3])
map("usa")
map_data <- points(x = ithaca$Var1,y=ithaca$Var2,col="pink",pch=19,cex=0.2)
title(main="reachable grid points from Ithaca with x=75")
print(sprintf("The proportion of all grids in Continental USA which can be reached from Ithaca when x = 75 miles is about %.5f",proportion.val(ithaca)))


```

```{r fig.width= 8, fig.height= 8}
# x = 100 miles
ithaca <- reachable_points(lonlat_usa,ithaca_lonlat,100,df = df_in_USA, ad = continent_df[,1:3])
map("usa")
map_data <- points(x = ithaca$Var1,y=ithaca$Var2,col="pink",pch=19,cex=0.2)
title(main="reachable grid points from Ithaca with x=75")

proportion.val(ithaca)
print(sprintf("The proportion of all grids in Continental USA which can be reached from Ithaca when x = 100 miles is about %.5f",proportion.val(ithaca)))
```

### Part2 Q3
```{r}
library(fields)

fields::quilt.plot(prop_reachable_75[,1:2],prop_reachable_75[,3],main="proportion of reachable grid poins for x = 75")
US(add =TRUE, col="grey",lwd=2)

fields::quilt.plot(prop_reachable_100[,1:2],prop_reachable_100[,3],main="proportion of reachable grid poins for x = 100")
US(add =TRUE, col="grey",lwd=2)

```

### Part2 Q4

### Scenario B
```{r}
## x = 75 miles
ithaca_b <- reachable_points(lonlat_usa,ithaca_lonlat,75, df = direct_from_b, ad = continent_df[,1:3])
map("usa")
map_data <- points(x = ithaca_b$Var1,y=ithaca_b$Var2,col="pink",pch=19,cex=0.2)
title(main="Scenario B: reachable grid points from Ithaca with x=75")

proportion.val(ithaca)
print(sprintf("The proportion of all grids in Continental USA which can be reached from Ithaca when x = 75 miles is about %.5f",proportion.val(ithaca)))

## x = 75 miles
ithaca_b <- reachable_points(lonlat_usa,ithaca_lonlat,100, df = direct_from_b, ad = continent_df[,1:3])
map("usa")
map_data <- points(x = ithaca_b$Var1,y=ithaca_b$Var2,col="pink",pch=19,cex=0.2)
title(main="Scenario B: reachable grid points from Ithaca with x=100")

proportion.val(ithaca)
print(sprintf("The proportion of all grids in Continental USA which can be reached from Ithaca when x = 100 miles is about %.5f",proportion.val(ithaca)))
```

